__name__ = "python-wuphf"
__version__ = "0.1.0"
__author__ = "Derek Merck"
__author_email__ = "derek.merck@ufl.edu"
__desc__ = "PyCRUD messenger endpoints"
__url__ = "https://github.com/derekmerck/python-wuphf"
